server:
    port: 8769

spring:
    application:
        name: spring-cloud-config-server
    security:
        user:
            name: admin
            password: admin
    boot:
        admin:
            client:
                url: http://127.0.0.1:8000                      ## 指向 spring boot admin server
                username: admin
                password: admin
                instance:
                    service-base-url:  http://127.0.0.1:${server.port}    ## 通过 war 方式部署的时候，需要指定被注册的app 的访问 url
    rabbitmq:
        host: 119.3.25.179
        port: 5672
        username: admin
        password: admin
    cloud:
        bus:
            enabled: true
            ## 开启消息跟踪
            trace:
                enabled: true
            refresh:
                enabled: true
        config:
            server:
                native:
                    search-locations: classpath:/config
                bootstrap: true
    profiles:
        active: native


eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
        fetchRegistry: true

management:
    endpoints:

        web:
            exposure:
                include: "*"
    endpoint:
        env:
            enabled: true


logging:
    config: classpath:logback-${spring.profiles.active}.xml

foo:
    foo-version: 5